package one.demo;

import io.github.centrifugal.centrifuge.Client;
import io.github.centrifugal.centrifuge.ConnectedEvent;
import io.github.centrifugal.centrifuge.ConnectingEvent;
import io.github.centrifugal.centrifuge.DisconnectedEvent;
import io.github.centrifugal.centrifuge.DuplicateSubscriptionException;
import io.github.centrifugal.centrifuge.EventListener;
import io.github.centrifugal.centrifuge.MessageEvent;
import io.github.centrifugal.centrifuge.Options;
import io.github.centrifugal.centrifuge.PublicationEvent;
import io.github.centrifugal.centrifuge.PublishResult;
import io.github.centrifugal.centrifuge.ResultCallback;
import io.github.centrifugal.centrifuge.SubscribedEvent;
import io.github.centrifugal.centrifuge.Subscription;
import io.github.centrifugal.centrifuge.SubscriptionErrorEvent;
import io.github.centrifugal.centrifuge.SubscriptionEventListener;

import java.nio.charset.Charset;
import java.nio.charset.StandardCharsets;
import java.util.Objects;
import java.util.Scanner;

public class App {

    // generated by centrifugo subCommand
    private final static String TOKEN = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJqYXZhLWRlbW8tMSIsImV4cCI6MTc2Mjg1MDkxNywiaWF0IjoxNzYyMjQ2MTE3fQ.rRWkV3OBvwBAFkn7mdJHPizbSRm4K-IwGKlEPiPnslU";

    // generated by TokenGenerator
    private final static String TOKEN2 = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJhdXRoMCIsInN1YiI6ImphdmEtZGVtby0xIiwiaWF0IjoxNzYyNDEyOTcwLCJleHAiOjE3NjMwMTc3NzB9.bKjEXIoDcUcHJtKvQq8HvD-JNmYlic8ulGu57mtHwG0";

    private static Client CLIENT = null;

    public static void main(String[] args) {
        start();
        // System.out.println(TokenGenerator.generateJwtToken());
    }

    private static void start() {
        new Thread(() -> {
            EventListener listener = new EventListener() {
                @Override
                public void onConnected(Client client, ConnectedEvent event) {
                    System.out.println("connected");
                }
                @Override
                public void onConnecting(Client client, ConnectingEvent event) {
                    System.out.printf("connecting: %s%n", event.getReason());
                }
                @Override
                public void onDisconnected(Client client, DisconnectedEvent event) {
                    System.out.printf("disconnected %d %s\n", event.getCode(), event.getReason());
                }

                @Override
                public void onMessage(Client client, MessageEvent event) {
                    System.out.printf("message %s\n", new String(event.getData()));
                }
            };

            Options opts = new Options();
            opts.setName("java-demo-1");
            opts.setToken(TOKEN2);

            CLIENT = new Client("ws://localhost:8000/connection/websocket", opts, listener);
            Subscription subscription = null;
            try {
                subscription = CLIENT.newSubscription("channel", new SubscriptionEventListener() {
                    @Override
                    public void onPublication(Subscription sub, PublicationEvent event) {
                        System.out.printf("publication from channel:%s data:%s\n", sub.getChannel(), new String(event.getData(), Charset.defaultCharset()));
                    }

                    @Override
                    public void onSubscribed(Subscription sub, SubscribedEvent event) {
                        System.out.printf("subscribed %s\n", new String(event.getData()));
                    }

                    @Override
                    public void onError(Subscription sub, SubscriptionErrorEvent event) {
                        System.out.printf("subscribe error %s\n", event.getError().getCause());
                    }
                });
            } catch (DuplicateSubscriptionException e) {
                throw new RuntimeException(e);
            }
            subscription.subscribe();
            CLIENT.connect();
        }).start();
        Scanner sc = new Scanner(System.in);
        System.out.println("started");
        while (sc.hasNext()) {
            String s = sc.nextLine();
            if ("send".equals(s)) {
                send();
            }
        }
    }

    /*==================================== SEND MESSAGE ==========================================*/
    public static void send() {
        String jsonStr = String.format("{\"value\": \"from-java-for-all\", \"timestamp\": %d}", System.currentTimeMillis());
        CLIENT.getSubscription("channel").publish(jsonStr.getBytes(StandardCharsets.UTF_8), new ResultCallback<PublishResult>() {
            @Override
            public void onDone(Throwable e, PublishResult result) {
                if (null != e) {
                    e.printStackTrace();
                    return;
                }
                System.out.printf("message published! result:%s\n", Objects.nonNull(result.toString()));
            }
        });
    }

}
